.github/workflows/docker-publish.yml, oracle-server-ui/Dockerfile
This automates publishing of docker images everytime a commit is merged into CI for the `oracle-server-ui` project
https://hub.docker.com/repository/docker/bitcoinscala/oracle-server-ui
=> 2021 09 10 UI dockerfile

.github/workflows/Compile.yml
=> Remove node 10 support

oracle-server-ui/src/app/component/alert/alert.component.scss, oracle-server-ui/src/app/event-detail/event-detail.component.html, oracle-server-ui/src/app/event-detail/event-detail.component.ts, oracle-server-ui/src/app/oracle/oracle.component.html, oracle-server-ui/src/assets/i18n/en.json
Addresses know wants for signing success message and issue updating state when signing digit outcomes
=> Show outcome signing success, update event outcome when signing digits

Dockerfile, oracle-server-ui-proxy/build-config.ts, oracle-server-ui-proxy/build/buildVersion.js, oracle-server-ui-proxy/package-lock.json, oracle-server-ui-proxy/package.json, oracle-server-ui-proxy/server.ts, oracle-server-ui/src/app/oracle/oracle.component.html, oracle-server-ui/src/app/oracle/oracle.component.scss, oracle-server-ui/src/app/oracle/oracle.component.ts, oracle-server-ui/src/assets/i18n/en.json, oracle-server-ui/src/service/message.service.ts, oracle-server-ui/src/type/oracle-server-types.ts, oracle-server-ui/src/type/proxy-server-types.ts, oracle-server-ui/src/util/message-util.ts
At this point, all build data is from git. We could inject version/build data from elsewhere as well like official build version, but I don't know where that comes from / how to produce it in this context.
=> Make BuildConfig from git state at build time and share with UI

oracle-server-ui/src/app/new-event/new-event.component.html, oracle-server-ui/src/app/new-event/new-event.component.ts, oracle-server-ui/src/type/oracle-server-message.ts, oracle-server-ui/src/type/oracle-server-types.ts, oracle-server-ui/src/util/message-util.ts
=> Maturation Time minDate and code cleanup

oracle-server-ui/src/assets/i18n/en.json
=> Rename event -> announcement in the UI

oracle-server-ts/README.md, oracle-server-ts/dist/index.d.ts, oracle-server-ts/dist/index.js, oracle-server-ts/dist/message-util.d.ts, oracle-server-ts/dist/message-util.js, oracle-server-ts/dist/oracle-server-message.d.ts, oracle-server-ts/dist/oracle-server-message.js, oracle-server-ts/dist/oracle-server-types.d.ts, oracle-server-ts/dist/oracle-server-types.js, oracle-server-ts/dist/util.d.ts, oracle-server-ts/dist/util.js, oracle-server-ts/lib/index.ts, oracle-server-ts/lib/message-util.ts, oracle-server-ts/lib/oracle-server-message.ts, oracle-server-ts/lib/oracle-server-types.ts, oracle-server-ts/lib/util.ts, oracle-server-ts/package-lock.json, oracle-server-ts/package.json, oracle-server-ts/test.js, oracle-server-ts/tsconfig.json
Not ready for prime time, but demo of what a NodeJS server-side library could look like.
=> Starting point for oracle-server-ts

.github/workflows/npm-publish.yml, oracle-server-ts/package-lock.json
Combine these two steps so we run `npm install` in the correct directory
=> 2021 10 11 npm publish bug

common-ts/lib/index.ts, oracle-server-ui-proxy/config.json, oracle-server-ui-proxy/server-config.ts, oracle-server-ui-proxy/server.ts, wallet-server-ui-proxy/config.json, wallet-server-ui-proxy/middleware/auth.ts, wallet-server-ui-proxy/middleware/backup.ts, wallet-server-ui-proxy/middleware/logger.ts, wallet-server-ui-proxy/package-lock.json, wallet-server-ui-proxy/package.json, wallet-server-ui-proxy/routes/proxy.ts, wallet-server-ui-proxy/server.ts, wallet-server-ui-proxy/type/run-config.ts, wallet-server-ui-proxy/type/server-config.ts, wallet-server-ui/Dockerfile, wallet-server-ui/package-lock.json, wallet-server-ui/src/app/app-routing.module.ts, wallet-server-ui/src/app/app.component.ts, wallet-server-ui/src/app/component/debug/debug.component.ts, wallet-server-ui/src/app/component/header/header.component.ts, wallet-server-ui/src/app/guard/auth-guard.ts, wallet-server-ui/src/environments/environment.ts, wallet-server-ui/src/service/auth.service.ts, wallet-server-ui/src/service/message.service.ts, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/service/websocket.service.ts, wallet-ts/lib/index.ts
This adds support for API and websocket authorization to wallet-server-ui-proxy / wallet-server-ui. Adds new uiPassword to oracle-server-ui-proxy, but does not implement any other changes there yet.
Tested locally with bitcoin-s server password set and not set. Tested in docker environment with attached docker-compose.yml.
[docker-compose.yml.txt](https://github.com/bitcoin-s/bitcoin-s-ts/files/7879225/docker-compose.yml.txt)
=> Add bitcoin-s API and websocket authorization

wallet-server-ui/src/app/app-routing.module.ts, wallet-server-ui/src/app/component/about/about.component.ts, wallet-server-ui/src/app/component/header/header.component.html, wallet-server-ui/src/app/component/login/login.component.html, wallet-server-ui/src/app/component/login/login.component.ts, wallet-server-ui/src/service/wallet-state-service.ts
This exposes an about route outside of authorization to help with debugging potential issues in the future.
=> Move wallet /about outside of auth

oracle-server-ui/src/app/announcement-detail/announcement-detail.component.html, oracle-server-ui/src/app/new-announcement/new-announcement.component.html, oracle-server-ui/src/app/new-announcement/new-announcement.component.scss, oracle-server-ui/src/app/new-announcement/new-announcement.component.ts, oracle-server-ui/src/app/oracle/oracle.component.ts, oracle-server-ui/src/app/sign-message/sign-message.component.html, oracle-server-ui/src/assets/i18n/en.json
fixes #66 
Also adds autocompete=“off” to fields.
=> Refactor to two create announcement forms, fix outcomes trim

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
=> Add axis labels to charts

wallet-server-ui/src/app/component/debug/debug.component.html, wallet-server-ui/src/app/component/debug/debug.component.scss, wallet-server-ui/src/app/component/debug/debug.component.ts, wallet-server-ui/src/assets/i18n/en.json
=> Expose ignoreCreationTime flag for rescan

oracle-server-ui/src/app/new-announcement/new-announcement.component.ts
This should prevent double clicking Create
=> Set loading flag during create announcement

oracle-server-ui/src/app/about/about.component.html, oracle-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/app/component/about/about.component.html
=> Add telegram to About pages

wallet-server-ui/src/service/auth.service.ts
This keeps async actions near the logout timer expiring from showing 400 errors to the user.
=> Shorten logout timer by a fudge factor to avoid 400 errors near logout

oracle-server-ui-proxy/type/run-config.ts, wallet-server-ui-proxy/type/run-config.ts
Fixes #90 
I will update the Krystal Bull and Suredbits Wallet docker-compose.ymls with the 1.9 push to Umbrel repo.
=> Change BACKUP_PATH to BITCOIN_S_HOME

common-ts/package-lock.json, common-ts/package.json, oracle-server-ts/package-lock.json, oracle-server-ts/package.json, oracle-server-ui-proxy/package-lock.json, oracle-server-ui-proxy/package.json, oracle-server-ui/package-lock.json, oracle-server-ui/package.json, wallet-server-ui-proxy/package-lock.json, wallet-server-ui-proxy/package.json, wallet-server-ui/package-lock.json, wallet-server-ui/package.json, wallet-ts/package-lock.json, wallet-ts/package.json
TODO : Roll BACKUP_PATH to BITCOIN_S_HOME on Umbrel docker-compose.yml files once this merges.
=> Roll up all packages and dependencies to 1.9.0

.github/workflows/Compile.yml, wallet-server-ui/src/app/app.component.spec.ts, wallet-server-ui/src/app/dialog/logout/logout.component.spec.ts
Get dependencies installed before building wallet-server-ui
=> Install wallet-server-ui dependencies ahead of build

common-ts/package.json, oracle-server-ts/package.json, oracle-server-ui-proxy/package.json, oracle-server-ui/package.json, wallet-server-ui-proxy/package.json, wallet-server-ui/package.json, wallet-ts/package.json
=> Add repository tag to package.jsons

wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/new-offer/new-offer.component.ts, wallet-server-ui/src/assets/i18n/en.json
=> Add warning for enum contracts that don't pay you total collateral

wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.html, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.scss, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/wallet-state-service.ts
Allows popping up New Address dialog on unfunded addresses to get back to QR Code view.
=> Show Funded and Unfunded address lists on Wallet

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.scss, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts, wallet-server-ui/src/app/component/contracts/contracts.component.ts, wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/new-offer/new-offer.component.scss, wallet-server-ui/src/app/component/new-offer/new-offer.component.ts, wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.html, wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.scss, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/auth.service.ts, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/service/websocket.service.ts, wallet-server-ui/src/styles.scss, wallet-server-ui/src/util/utils.ts, wallet-server-ui/src/util/validators.ts
=> Event id sorting

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts, wallet-server-ui/src/app/component/build-accept-offer/build-accept-offer.component.html, wallet-server-ui/src/app/component/build-accept-offer/build-accept-offer.component.ts, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/new-offer/new-offer.component.ts, wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.html, wallet-server-ui/src/app/dialog/send-funds-dialog/send-funds-dialog.component.ts, wallet-server-ui/src/util/utils.ts
Also turns of spellcheck on some input fields to avoid underline
=> Add trimOnPaste() and use across application

wallet-server-ui/src/app/app-routing.module.ts, wallet-server-ui/src/app/app.component.ts, wallet-server-ui/src/app/app.module.ts, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.scss, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts, wallet-server-ui/src/app/component/build-accept-offer/build-accept-offer.component.html, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.scss, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/app/component/contracts/contracts.component.html, wallet-server-ui/src/app/component/contracts/contracts.component.ts, wallet-server-ui/src/app/component/header/header.component.html, wallet-server-ui/src/app/component/header/header.component.scss, wallet-server-ui/src/app/component/header/header.component.ts, wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/offers/offers.component.html, wallet-server-ui/src/app/component/offers/offers.component.scss, wallet-server-ui/src/app/component/offers/offers.component.spec.ts, wallet-server-ui/src/app/component/offers/offers.component.ts, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.html, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.scss, wallet-server-ui/src/app/shared/modules/material/material.module.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/dlc-service.ts, wallet-server-ui/src/service/offer-service.ts, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/service/websocket.service.ts, wallet-server-ui/src/styles.scss, wallet-server-ui/src/type/wallet-server-types.ts, wallet-server-ui/src/util/utils.ts
This runs on top of https://github.com/bitcoin-s/bitcoin-s/pull/4129
Adds /offers and header link, refactors dlc and offer specific state into independent services, show message from IncomingOffer when displaying Accept Offer sidebar.
For some reason Executing on the Accept Offer is not working, returning a 'failure' response. Haven't figured out why yet, but this will let you create, delete, and list Incoming Offers and see what's going on in its current state.
=> Add Offer Mailbox

wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html, wallet-server-ui/src/app/component/contracts/contracts.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/type/wallet-server-types.ts
To match https://github.com/bitcoin-s/bitcoin-s/pull/4146
=> Change DLCContract.tempContractId to temporaryContractId

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html, wallet-server-ui/src/app/component/offers/offers.component.html, wallet-server-ui/src/app/component/offers/offers.component.ts, wallet-server-ui/src/type/wallet-server-types.ts, wallet-ts/lib/type/core-types.ts
Goes with https://github.com/bitcoin-s/bitcoin-s/pull/4148
=> Offer.offerCollateralSatoshis to offerCollateral

wallet-server-ui/src/util/utils.ts
Fix every-other paste bug with trimOnPaste()
=> Fix trimOnPaste()

wallet-server-ui/src/app/component/debug/debug.component.html, wallet-server-ui/src/app/component/debug/debug.component.scss, wallet-server-ui/src/app/component/debug/debug.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/styles.scss
=> Advanced gettransaction functionality

wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/new-offer/new-offer.component.scss
=> Disallow editing numeric outcome endpoints

wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/type/wallet-server-types.ts, wallet-ts/lib/index.ts, wallet-ts/lib/type/wallet-types.ts
=> Add Get Offer Hex to Contract Detail and wallet-ts

wallet-server-ui/src/app/app.module.ts, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/app/dialog/fee-rate-dialog/fee-rate-dialog.component.html, wallet-server-ui/src/app/dialog/fee-rate-dialog/fee-rate-dialog.component.scss, wallet-server-ui/src/app/dialog/fee-rate-dialog/fee-rate-dialog.component.spec.ts, wallet-server-ui/src/app/dialog/fee-rate-dialog/fee-rate-dialog.component.ts, wallet-server-ui/src/service/dlc-service.ts, wallet-server-ui/src/service/websocket.service.ts, wallet-server-ui/src/styles.scss
=> Add Bump Fee button to Funding Tx

wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/service/websocket.service.ts
=> Show ConfirmationDialog when receiving DLC.broadcast state change

wallet-server-ui/src/app/app.module.ts, wallet-server-ui/src/app/component/address-label/address-label.component.html, wallet-server-ui/src/app/component/address-label/address-label.component.scss, wallet-server-ui/src/app/component/address-label/address-label.component.spec.ts, wallet-server-ui/src/app/component/address-label/address-label.component.ts, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.html, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.scss, wallet-server-ui/src/app/component/wallet-balance/wallet-balance.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/address.service.ts, wallet-server-ui/src/service/backend.service.ts, wallet-server-ui/src/service/offer-service.ts, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/service/websocket.service.ts, wallet-server-ui/src/styles.scss, wallet-server-ui/src/type/wallet-server-types.ts, wallet-ts/lib/index.ts, wallet-ts/lib/type/wallet-types.ts, wallet-ts/test/basic-tests.ts
Runs over https://github.com/bitcoin-s/bitcoin-s/pull/4175
=> Add address labeling

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html, wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/new-offer/new-offer.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/util/validators.ts
=> Don't allow using own Tor DLC Host Address in peerAddress fields

wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/websocket.service.ts
Add eventId to broadcast dialogs to give user an anchor for async dialog popups.
=> Add eventId to broadcast dialogs

wallet-server-ui/src/app/component/address-label/address-label.component.ts, wallet-server-ui/src/app/dialog/new-address-dialog/new-address-dialog.component.html, wallet-server-ui/src/app/dialog/new-address-dialog/new-address-dialog.component.scss, wallet-server-ui/src/app/dialog/new-address-dialog/new-address-dialog.component.ts
=> Allow labeling new addresses in dialog

common-ts/package-lock.json, oracle-server-ts/package-lock.json, oracle-server-ui-proxy/package-lock.json, oracle-server-ui/.gitignore, oracle-server-ui/package-lock.json, wallet-server-ui-proxy/package-lock.json, wallet-server-ui-proxy/package.json, wallet-server-ui/.gitignore, wallet-server-ui/package-lock.json, wallet-server-ui/src/service/localstorage.service.ts, wallet-server-ui/src/styles.scss, wallet-ts/package-lock.json
Runs `npm update` across projects and add localStorage service that will be used in the Thunder Games branch, but I would like to have on master. Makes stroked outline icon buttons a little smaller.
=> Updates before Bitcoin 2022 feature branch

wallet-server-ui/src/app/component/build-accept-offer/build-accept-offer.component.html
Update tutorial video to include the new UI
=> update youtube video include the new UI

oracle-server-ui/Dockerfile, wallet-server-ui/Dockerfile
Trying to fix Docker image builds
```
#20 [linux/amd64 builder 9/9] RUN npm run build
#20 0.387 
#20 0.387 > oracle-server-ui-proxy@1.9.1 build
#20 0.387 > node --loader ts-node/esm --es-module-specifier-resolution=node ./build/buildVersion.ts && ./fixup.sh && cp config.json build.json ./dist/cjs && cp config.json build.json ./dist/mjs
#20 0.387 
#20 0.428 (node:18) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
#20 0.428 (Use `node --trace-warnings ...` to show where the warning was created)
#20 0.429 (node:18) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
#20 2.603 /build/node_modules/ts-node/src/index.ts:820
#20 2.603     return new …
```
=> Add npm run build to monorepo root on Dockerfile builds

wallet-server-ui/src/app/app-routing.module.ts, wallet-server-ui/src/app/app.module.ts, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html, wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts, wallet-server-ui/src/app/component/contacts/contacts.component.html, wallet-server-ui/src/app/component/contacts/contacts.component.scss, wallet-server-ui/src/app/component/contacts/contacts.component.spec.ts, wallet-server-ui/src/app/component/contacts/contacts.component.ts, wallet-server-ui/src/app/component/header/header.component.html, wallet-server-ui/src/app/component/header/header.component.scss, wallet-server-ui/src/app/component/network/network.component.html, wallet-server-ui/src/app/component/network/network.component.scss, wallet-server-ui/src/app/component/new-offer/new-offer.component.html, wallet-server-ui/src/app/component/new-offer/new-offer.component.ts, wallet-server-ui/src/app/component/offers/offers.component.html, wallet-server-ui/src/app/component/offers/offers.component.scss, wallet-server-ui/src/app/component/offers/offers.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/scss/animations.scss, wallet-server-ui/src/service/contact-service.ts, wallet-server-ui/src/service/offer-service.ts, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/styles.scss, wallet-server-ui/src/type/wallet-server-types.ts, wallet-ts/lib/index.ts, wallet-ts/lib/type/blockchain-types.ts, wallet-ts/lib/type/wallet-types.ts
Replaces #144 
Adds wallet Contact List, Tor Starting awareness and polling, and wallet-ts types and functions for Offers and Contacts.
Tor Starting
Offer Peer labeling from Contacts
=> Add wallet Contact List, torStarting, wallet-ts offer/contact types

oracle-electron-ts/makeBin.sh, oracle-server-ui/Dockerfile, wallet-electron-ts/makeBin.sh, wallet-server-ui/Dockerfile
Adding to ease building electron apps with github workflows
=> Allow electron building with folder vs zip backend

common-ts/package.json, oracle-server-ts/package.json, oracle-server-ui-proxy/package.json, oracle-server-ui/package.json, package.json, wallet-server-ui-proxy/package.json, wallet-server-ui/package.json, wallet-ts/package.json
=> Version rollup to 1.9.2

oracle-electron-ts/src/index.ts, wallet-electron-ts/src/index.ts
This gets the bitcoin-s server started in WIndows electron apps and gets logging to file working. Server still does not shut down gracefully.
=> Fix server process path and windows file logging

wallet-server-ui/Dockerfile, wallet-server-ui/buildDocker.sh, wallet-server-ui/src/app/component/contacts/contacts.component.ts, wallet-server-ui/src/app/component/debug/debug.component.ts, wallet-server-ui/src/app/component/header/header.component.scss, wallet-server-ui/src/app/component/import-export/import-export.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/service/websocket.service.ts
Initializes some core server data earlier so the user can see it while syncing chain.
Put 15 second debounce on any reinitialization calls as sanity check.
=> Add 15 second delays to any calls to re-run state initialization

oracle-server-ts/lib/index.ts, oracle-server-ts/lib/type/oracle-server-types.ts, oracle-server-ts/test.js, oracle-server-ui/src/app/announcement-detail/announcement-detail.component.ts, oracle-server-ui/src/app/app.component.html, oracle-server-ui/src/app/app.component.ts, oracle-server-ui/src/app/component/advanced/advanced.component.html, oracle-server-ui/src/app/component/advanced/advanced.component.ts, oracle-server-ui/src/app/configuration/configuration.component.html, oracle-server-ui/src/app/configuration/configuration.component.scss, oracle-server-ui/src/app/dialog/confirmation/confirmation.component.html, oracle-server-ui/src/app/dialog/confirmation/confirmation.component.ts, oracle-server-ui/src/app/oracle/oracle.component.ts, oracle-server-ui/src/assets/i18n/en.json, oracle-server-ui/src/service/oracle-state.service.ts, oracle-server-ui/src/type/oracle-server-types.ts, oracle-server-ui/src/util/oracle-server-util.ts
Runs over https://github.com/bitcoin-s/bitcoin-s/pull/4617
Cleaned up mouse click outside of right side menus messing with state when opening them again.
=> Export staking address wif support

oracle-electron-ts/package-lock.json, oracle-server-ui/src/app/app.component.ts, oracle-server-ui/src/service/auth.service.ts, oracle-server-ui/src/service/message.service.ts, oracle-server-ui/src/service/oracle-state.service.ts, wallet-electron-ts/package-lock.json, wallet-server-ui/src/service/auth.service.ts
Aligns Krystal Bull code with Suredbits Wallet code and handles refreshToken properly after proxy restarts.
=> Fix Krystal Bull refreshToken handling

build-oracle-electron.sh, build-wallet-electron.sh
Now use the 1.9.3 backend artifacts for the build scripts
=> 2022 09 02 update electron sh

wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/wallet-state-service.ts, wallet-server-ui/src/service/websocket.service.ts
=> Show a restart dialog after 2 minutes if torStarted does not set

wallet-server-ui/src/app/component/contacts/contacts.component.html, wallet-server-ui/src/app/component/contacts/contacts.component.scss, wallet-server-ui/src/app/component/contacts/contacts.component.ts, wallet-server-ui/src/assets/i18n/en.json, wallet-server-ui/src/service/contact-service.ts, wallet-server-ui/src/service/websocket.service.ts, wallet-server-ui/src/type/wallet-server-types.ts, wallet-ts/lib/type/dlc-types.ts
Adds buttons to call `checkconnection` and show status from call.
=> Frontend for checkconnection message

wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
Fixes contact association for Create Offer form
=> Fix DLC Contact association

oracle-server-ui/src/app/announcement-detail/announcement-detail.component.html, oracle-server-ui/src/app/announcement-detail/announcement-detail.component.scss, oracle-server-ui/src/app/announcement-detail/announcement-detail.component.ts, oracle-server-ui/src/app/component/advanced/advanced.component.html, oracle-server-ui/src/app/component/advanced/advanced.component.scss, oracle-server-ui/src/app/login/login.component.html, oracle-server-ui/src/app/new-announcement/new-announcement.component.html, oracle-server-ui/src/app/new-announcement/new-announcement.component.scss, oracle-server-ui/src/app/new-announcement/new-announcement.component.ts, oracle-server-ui/src/app/oracle/oracle.component.html, oracle-server-ui/src/app/oracle/oracle.component.scss, oracle-server-ui/src/app/oracle/oracle.component.ts, oracle-server-ui/src/assets/i18n/en.json, oracle-server-ui/src/styles.scss, oracle-server-ui/src/util/oracle-server-util.ts
Make enum outcomes distinct, confirm new announcement close, add Advanced section label, outcome formatting
=> Make enum outcomes distinct

oracle-server-ui/src/app/about/about.component.html, wallet-server-ui/src/app/component/about/about.component.html
Add Krystal Bull / Suredbits Wallet youtube tutorials to the resource page.
=> Add links to youtube tutorials to resource page
