bitcoin-s/bitcoin-s-ts

.github/workflows/docker-publish.yml
Dockerfile
oracle-server-ui/package-lock.json

This PR adds support for publishing arm64 docker images to dockerhub: 
https://hub.docker.com/repository/docker/bitcoinscala/oracle-server-ui

2021 09 10 multiplatform docker

---

.github/workflows/Compile.yml
Dockerfile

Upgrades our node runtime to 16 in docker images and adds node 16 to CI. 
This PR also drops node 12 testing on CI.

2021 09 22 node 16

---

.github/workflows/oracle-server-rpc-tests.yml

Testing this on CI, it should start a docker container running the latest CI image published for the oracle-server on dockerhub 
https://hub.docker.com/r/bitcoinscala/bitcoin-s-oracle-server
This should allow us to run automated tests everytime we merge things into master against our Scala backend. Hopefully this complements #14

Add workflow to start up docker container for oracle server

---

.github/workflows/oracle-server-rpc-tests.yml

Add scripts to actually run `npm run test` inside of oracle-server-ts

Run oracle server rpc tests on CI

---

oracle-server-ts/lib/index.ts
oracle-server-ts/test/announcement-tests.ts
oracle-server-ui-proxy/server.ts
oracle-server-ui/package-lock.json
oracle-server-ui/package.json
oracle-server-ui/src/app/announcement-detail/announcement-detail.component.html
oracle-server-ui/src/app/announcement-detail/announcement-detail.component.scss
oracle-server-ui/src/app/announcement-detail/announcement-detail.component.ts
oracle-server-ui/src/app/configuration/configuration.component.scss
oracle-server-ui/src/app/new-announcement/new-announcement.component.html
oracle-server-ui/src/app/new-announcement/new-announcement.component.scss
oracle-server-ui/src/app/new-announcement/new-announcement.component.ts
oracle-server-ui/src/app/oracle/oracle.component.scss
oracle-server-ui/src/app/oracle/oracle.component.ts
oracle-server-ui/src/app/sign-message/sign-message.component.html
oracle-server-ui/src/assets/i18n/en.json
oracle-server-ui/src/service/oracle-state.service.ts
oracle-server-ui/src/type/proxy-server-types.ts

Adds delete operations to the UI, adds some state to the Announcement Detail pane and operation buttons, adds LOG_PATH to proxy to host log file on Umbrel at arbitrary location.

Add delete announcement/attestation from UI, add LOG_PATH to proxy

---

.github/workflows/npm-publish.yml
oracle-server-ts/package-lock.json
oracle-server-ts/package.json

Publishes oracle-server rpc library on npm
https://www.npmjs.com/package/@bitcoin-s-ts/oracle-server-ts
This is the workflow i decided to go with: https://github.com/JS-DevTools/npm-publish
An open question is versioning, but if I understand the `check-version` setting from `npm-publish` it will check if the versions are the same as available on npm, and if they are the same, it doesn't publish. 
I can't really test this until 
1. We merge this PR into master
2. We merge a second PR into master and confirm that the build didn't trigger
3. We merge a 3rd PR that bumps the version and confirm that the new version shows up on npmjs

2021 10 10 oracle server npm publish

---

.github/workflows/npm-publish.yml
oracle-server-ts/package.json

fixes a bug introduced in #28 
`npm-publish` action works by looking up the `latest` tag on npmjs. I happened to publish version `0.0.1-LOCAL` with the latest tag on our registry
The `check-version` features for `npm-publish` works like this: 
It checks the combination of version (`0.0.1-LOCAL`) and the the local version (`0.0.1`) and finds the semantically versioned difference. However, since I already published a `0.0.1` that did NOT have the `latest` tag, `npm-publish` doesn't recognize it. 
npmjs itself recognizes that it has a (`0.0.1`) and fails to publish. 
https://github.com/bitcoin-s/bitcoin-s-ts/runs/3862187376#step:7:57
The only way i can see of how to get around this is by bumping the `oracle-server-ts` project to 0.0.2. I cannot see how to delete the `0.0.1-LOCAL` version on …

2021 10 11 npm publish bug

---

wallet-server-ui/src/service/wallet-state-service.ts

Handle situation with 'estimatefee' throwing 500 error when there is not enough data to estimate a network fee.

Handle server 500 error on 'estimatefee'

---

wallet-server-ui/package-lock.json
wallet-server-ui/package.json
wallet-server-ui/src/app/app.module.ts
wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html
wallet-server-ui/src/app/component/accept-offer/accept-offer.component.ts
wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html
wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
wallet-server-ui/src/app/component/contracts/contracts.component.ts
wallet-server-ui/src/app/component/new-offer/new-offer.component.html
wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
wallet-server-ui/src/assets/i18n/en.json

This adds payout graphs using the same chart.js library used on the Oracle Explorer. There are probably better options to think about long term, but this gets the feature in and working. Graphs live update as the user edits a numeric offer and render accepting the offer and show outcome if one exists on contract details.

Add payout graphs

---

.github/workflows/docker-publish.yml

We are seeing builds timeout when publishing to docker so bump the timeout for now as a stop gap. Over the long term we should look for a away to optimize the build.
https://github.com/bitcoin-s/bitcoin-s-ts/runs/5022835894?check_suite_focus=true#step:10:333

Bump docker publish timeout to 90 minutes

---

wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
wallet-server-ui/src/service/chart.service.ts
wallet-server-ui/src/util/utils.ts

This supports ranges of outcome values on numeric contracts.
Non-ranged:
I left the graph implementation as a point vs shading range which would take substantially more coding.

Support ranged outcome values

---

README.md

From a user
We do have README, just not at the top level. This PR adds a simple README at top level that directs to project specific README

Add top level README

---

.github/workflows/npm-publish.yml

fixes #88 
This should publish a `0.0.4` version of `wallet-ts` as there was never a version published. The way the workflows work is it checks `npmjs.com` if the version exists, it does not publish. If it does not exist, it publishes to `npmjs.com`
https://github.com/JS-DevTools/npm-publish

Implement publishing of the wallet-ts project

---

wallet-ts/package.json

There was a bug in #93 
This PR unmarks the wallet-ts package as private
https://github.com/bitcoin-s/bitcoin-s-ts/runs/5189810106?check_suite_focus=true#step:8:73

Remove private field on package.json so we can publish

---

wallet-ts/package.json

We need to add the organization qualifier to wallet-ts like we did for the oracle ts project here: 
https://github.com/bitcoin-s/bitcoin-s-ts/commit/818d64fc6b0601cd7a6fb4f07bc690603f3a2db8#diff-506e347f3b818889392e504234b3cec3272ea6e851f477c52ed472fcea5bf90aR2

Add bitcoin-s organization to wallet-ts library

---

.github/workflows/npm-publish.yml

Stll getting these. This PR tries to set the package `access` as public. This is a configuration setting from the workflow:
https://github.com/JS-DevTools/npm-publish
https://github.com/bitcoin-s/bitcoin-s-ts/runs/5190962300?check_suite_focus=true#step:8:72

Try to change access explicitly to public

---

.github/workflows/docker-publish.yml

Namely this removes the `[commit-hash]-SNAPSHOT` suffix that we put on our SNAPSHOT release images on docker.

Add docker workflows for tagged releases

---

.github/workflows/docker-publish.yml

This PR does
1. Removes the leading `v` prefix for detecting if we have a tag. We don't prefix our tags with `v`
2. Publishes the releases first rather than the SNAPSHOTs. This is moved to make it easier for me to test.

Removes the 'v' prefix for detecting a tag

---

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.html
wallet-server-ui/src/app/component/accept-offer/accept-offer.component.scss
wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html
wallet-server-ui/src/app/component/contract-detail/contract-detail.component.ts
wallet-server-ui/src/app/component/new-offer/new-offer.component.html
wallet-server-ui/src/app/component/new-offer/new-offer.component.scss
wallet-server-ui/src/app/component/new-offer/new-offer.component.ts
wallet-server-ui/src/app/component/offers/offers.component.html
wallet-server-ui/src/app/component/offers/offers.component.ts
wallet-server-ui/src/assets/i18n/en.json
wallet-server-ui/src/service/offer-service.ts
wallet-server-ui/src/styles.scss

This runs over https://github.com/bitcoin-s/bitcoin-s/pull/4153
Implements `offer-send` RPC endpoint functionality from New Offer sidebar adding offer to remote counterparty's `offers-list`.
I tested several sent and received offers between Mac and x64, tested with external payout address, and tested traditional exchange (now 'Text'), tested with recipient offline, tested re-send same offer.

Implement offer-send UI

---

wallet-server-ui/src/app/component/accept-offer/accept-offer.component.scss
wallet-server-ui/src/app/component/contract-detail/contract-detail.component.html
wallet-server-ui/src/app/component/contracts/contracts.component.html
wallet-server-ui/src/app/component/contracts/contracts.component.ts
wallet-server-ui/src/assets/i18n/en.json
wallet-server-ui/src/type/wallet-server-types.ts
wallet-ts/lib/type/wallet-types.ts

Shows a flag for isExternal payoutAddresses in the Contract List and shows the payout address and flag for isExternal in Contract Details. Clicking isExternal icon will copy address to clipboard.
I'm not completely happy with icon, but seemed best of arrow type icons I looked at in material design icons.

Show DLC.payoutAddress and isExternal flag

---

oracle-server-ui/Dockerfile
wallet-server-ui/Dockerfile

This is the error I see when trying to build `oracle-server-ui/Dockerfile` and `wallet-server-ui/Dockerfile` locally.
This PR upgrades the base docker image `node:16.15-buster-slim`

Upgrade docker base image to node:16.15-buster-slim

---

wallet-server-ui/src/app/component/login/login.component.ts
wallet-server-ui/src/service/auth.service.ts

Trying to get to the root of @CypherPoet's issue.
I think there's a scenario when the refreshToken could have been unset, causing an error to throw, and the route not to change to include` loggedOut`, and autoLogin not unsetting. This case should be covered in logout().
This also unsets autoLogin on any error, which may be over-broad, but seems like a good fallback if the initial analysis is wrong.

Disable autoLogin to unlock password entry on login error

---

wallet-server-ui/src/app/app.component.ts
wallet-server-ui/src/app/component/header/header.component.html
wallet-server-ui/src/app/component/header/header.component.scss
wallet-server-ui/src/app/component/network/network.component.html
wallet-server-ui/src/app/component/network/network.component.scss
wallet-server-ui/src/assets/i18n/en.json
wallet-server-ui/src/service/wallet-state-service.ts
wallet-server-ui/src/type/wallet-server-types.ts
wallet-ts/lib/type/blockchain-types.ts

This adds the `isinitialblockdownload` to the `getinfo` response and shows in the header and on the network page. This doesn't change anything about the startup state machine.

Add isinitialblockdownload flag to getinfo, show in network and header

---

wallet-server-ui/src/app/component/contract-detail/contract-detail.component.scss
wallet-server-ui/src/app/component/contracts/contracts.component.html
wallet-server-ui/src/app/component/contracts/contracts.component.scss
wallet-server-ui/src/app/component/contracts/contracts.component.ts
wallet-server-ui/src/styles.scss

Fixes a PNL column sorting bug on Contracts and adds red/green arrows and color from Contract Details.

Make PNL red and green on Contracts, Fix PNL sorting bug
